### ISSUE TITLE
Question about this good code

### ISSUE THREAD

**Issue by vslinuxdotnet** [FluBBaOfWard/ARM6569#1]
Hello,
I have stopped in this code and I need to ask a question.
Is possible to implement a Virtual MOS6569 in a RPI pico/pico2 micro controller to replace this old IC? 
Thanks

**Comment by FluBBaOfWard** [comment]
If I'm not mistaken the pico/pico2 use ARM cortex which doesn't use ARM32, only thumb(2). And my emulator is not very good to begin with. And making it (more than?) cycle accurate to act as an IC is not on the map.
